config/routes.rb
Trackkr002::Application.routes.draw do
  
  
  default_url_options :host => "localhost:3000" 

  resources :share_dashboards

  get "share/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :user_product_plan_graphs
  
  #get "password_resets/new"
  resources :password_resets

  resources :user_product_plan_datas do
   post 'edit_individual', :on => :collection
   put 'update_individual', :on => :collection
  end

  resources :product_plans

  resources :plan_values

  resources :friendships

  root :to => "trackkr_modules#index"
 
  resources :graphs

  resources :user_product_plans
  get 'user_product_plan_graphs/new/:user_product_plan_id' => 'user_product_plan_graphs#new', :as => :new_graph_plan
  get 'user_product_plans/product/:product_id' => 'user_product_plans#new', :as => "add_new_user_product_plan"
  get 'plan_values/product/:product_plan_id' => 'plan_values#index', :as => "plan_value_product_info"
# the above are named routes - so we can call them using :as and the url that will be matched

  resources :dashboards 
  
  
  match  "/sample_dashboard" => "info#sample_dashboard", :as => :sample_dashboard
  match  "/about" => "info#About", :as => :About
  match  "/partners" => "info#Partners", :as => :Partners
  match  "/contact" => "info#Contact", :as => :Contact
  match  "/carriers" => "info#Carriers", :as => :Carriers
  match  "/help" => "info#Help", :as => :Help
  
resources :t_categories do
  resources :products do
    put 'select', :on => :collection
  end
end

  resources :trackkr_modules do
    resources :t_categories
  end
 
  resources :user_sessions
  
  get "login" => "user_sessions#new", :as => "login"
  get "logout" => "user_sessions#destroy", :as => "logout"
  
  get "add_to_cart/:product_id" => "user_products#add_to_cart",:as=>"add_to_cart"
  get "add_to_cart/:product_id/friend/:friend_id" => "user_products#add_to_cart",:as=>"add_to_cart_with_frd"  
  
  get "user_search" => "friendships#search", :as => "user_search"
  get "send_invite" => "friendships#send_invite",:as =>"send_invite"
  resources :users

end

app/models/user_product_plan.rb
class UserProductPlan < ActiveRecord::Base
  belongs_to :product_plan
  belongs_to :user
  validates_presence_of :product_plan_id
  has_many :user_product_plan_datas, :dependent => :destroy
  has_many :user_product_plan_graphs, :dependent => :destroy
  validates_uniqueness_of :product_plan_id, :scope => :user_id, :message => 'You already have this Product'
end

app/controllers/user_product_plans_controller.rb
class UserProductPlansController < ApplicationController
  before_filter :require_user
  helper_method :sort_direction, :sort_column
  # GET /user_product_plans
  # GET /user_product_plans.xml
  def index
    @user_product_plans = UserProductPlan.order(sort_column + " " + sort_direction).paginate(:per_page => 5, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.js
      format.xml  { render :xml => @user_product_plans }
    end
  end

  # GET /user_product_plans/1
  # GET /user_product_plans/1.xml
  def show
    @user_product_plan = UserProductPlan.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user_product_plan }
    end
  end

  # GET /user_product_plans/new
  # GET /user_product_plans/new.xml
  def new
    @existing_user_product_plan = current_user.user_product_plans.find_all_by_product_id(params[:product_id])
    @user_product_plan = UserProductPlan.new
    @trackkr_modules = TrackkrModule.all
    session[:product_id] = params[:product_id]

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user_product_plan }
    end
  end

  # GET /user_product_plans/1/edit
  def edit
    @user_product_plan = UserProductPlan.find(params[:id])
  end
 

  # POST /user_product_plans
  # POST /user_product_plans.xml
  def create
    @existing_user_product_plan = current_user.user_product_plans.find_by_product_id(params[:product_id])
    #@plan_values = PlanValue.find_by_product_plan_id(params[:product_plan_id])
    @user_product_plan = current_user.user_product_plans.new(params[:user_product_plan])

    id = params[:user_product_plan][:product_plan_id]
    @day_count = PlanValue.find_last_by_product_plan_id(id)

    date = "#{params['plan']['date(1i)']}/#{params['plan']['date(2i)']}/#{params['plan']['date(3i)']}"
    if params[:start_end] == "start"
      #time = @user_product_plan.start_date
      @user_product_plan.start_date = date
    
      @user_product_plan.end_date = @user_product_plan.start_date + @day_count.day
    elsif params[:start_end] == "end"
      @user_product_plan.end_date = date

      @user_product_plan.start_date = @user_product_plan.end_date - @day_count.day

    end
    
    if @user_product_plan.save
      plan_days = @user_product_plan.product_plan.plan_values
      status = false
      plan_days.each do |plan_day|
        user_product_plan_data = @user_product_plan.user_product_plan_datas.new
        user_product_plan_data.training_date = @user_product_plan.start_date.nil? ? (@user_product_plan.end_date - plan_day.day.days) : (@user_product_plan.start_date + plan_day.day.days)
        user_product_plan_data.plan_distance = plan_day.distance
        user_product_plan_data.plan_speed = plan_day.speed
        user_product_plan_data.plan_time = plan_day.time
        user_product_plan_data.plan_notes = plan_day.notes
        status = user_product_plan_data.save
      end  
    end
    if params[:friend_id]
      @frd = Friend.find(params[:friend_id])
      @frd.status = "Approved"
      @frd.save
    end
    respond_to do |format|
      if status
        format.html { redirect_to(dashboards_path, :notice => 'User product plan was successfully created.') }
        format.xml  { render :xml => @user_product_plan, :status => :created, :location => @user_product_plan }
      else
        format.html { redirect_to(add_new_user_product_plan_path(:product_id => session[:product_id]), :notice => 'This product already exists') }
        format.xml  { render :xml => @user_product_plan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /user_product_plans/1
  # PUT /user_product_plans/1.xml
  def update
    @user_product_plan = UserProductPlan.find(params[:id])

    respond_to do |format|
      if @user_product_plan.update_attributes(params[:user_product_plan])
        format.html { redirect_to(user_product_plan_datas_path, :notice => 'User product plan was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user_product_plan.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_product_plans/1
  # DELETE /user_product_plans/1.xml
  def destroy
    @user_product_plan = UserProductPlan.find(params[:id])
    @user_product_plan.destroy
    @any_plans_left = current_user.user_product_plans

    respond_to do |format|
      unless @any_plans_left.blank?
        format.html { redirect_to(dashboards_url) }
        format.xml  { head :ok }
      else
        format.html {redirect_to(trackkr_modules_path)}
    end
  end
end

 private

  def sort_column
    params[:sort] || "id"
    #UserProductPlan.column_names.include?(params[:sort]) ? params[:sort] : "id"
  end
  
  def sort_direction
    params[:direction] || "asc"
    #%w["asc","desc"].include?(params[:sort_direction]) ? params[:sort_direction] :"asc"
  end
end

app/helpers/user_product_plans_helper.rb
module UserProductPlansHelper
end

app/views/user_product_plans/_form.html.erb
<%= form_for(@user_product_plan) do |f| %>
  <% if @user_product_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_product_plan.errors.count, "error") %> prohibited this user_product_plan from being saved:</h2>

      <ul>
      <% @user_product_plan.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
      </ul>
    </div>
  <% end %>
  <% if @existing_user_product_plan.count  >= 1 %>
  		<p>You already have a plan under product <%=@existing_user_product_plan.first.product_plan.product.name%> </p>
 	<%else%>
 	You are currently signed up for:
    <%@existing_user_product_plan.each do|existing_user_product_plan|%>
     <li><%= existing_user_product_plan.product_plan.product_plan_name%></li>
  <%end%>
  	If you would like to change or reset the plan, please reselect from the following options. 
 	Please note that all your previous entries will be deleted and lost forever!
  	
  <br>
  <br>
  <div class="field">
  	<%=f.hidden_field :product_id , :value => params[:product_id]%>
  	<%= f.label :product_plan_id %>
	<%product_plans = Product.find(params[:product_id]).product_plans%>
  	<%= f.collection_select :product_plan_id, product_plans, :id, :product_plan_name, :prompt => 'Select a Plan' %>
  </div>
  <div><%=radio_button_tag :start_end, "start",:checked => true%> Start Date <%=radio_button_tag :start_end, "end"%> End Date</div>
  <div class="field">
  	<%= date_select :plan, :date %>
  </div>

 <%= submit_tag "Add to Trackkr" %>
 <% end %>
<% end %>

app/views/user_product_plans/_user_product_plans.html.erb
<% @user_product_plans.each do |user_product_plan| %>
  <tr>
  	<td><%= user_product_plan.id %></td>
    <td><%= user_product_plan.user_id %></td>
    <td><%= user_product_plan.product_id %></td>
    <td><%= user_product_plan.product_plan_id %></td>
    <td><%= user_product_plan.start_date %></td>
    <td><%= user_product_plan.end_date %></td>
    <td><%= link_to 'Show', user_product_plan %></td>
    <td><%= link_to 'Edit', edit_user_product_plan_path(user_product_plan) %></td>
    <td><%= button_to 'Destroy', user_product_plan, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/user_product_plans/edit.html.erb
<h1>Editing user plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_product_plan %> |
<%= link_to 'Back', user_product_plans_path %>

app/views/user_product_plans/index.html.erb
<h1>Listing user_products</h1>

<table>
  <tr>
  	<th><%= sortable "id" %></th>
    <th><%= sortable "user_id" %></th>
    <th><%= sortable "product_id" %></th>
    <th><%= sortable "product_plan_id" %></th>
    <th><%= sortable "start_date"%></th>
    <th><%= sortable "end_date" %></th>
    <th></th>
  </tr>
<script type="text/javascript">
	
</script>

<div id='user_product_plans'><%= render 'user_product_plans' %> </div>

<br />
<%= will_paginate @user_product_plans%>

<%= link_to 'New User product', new_user_product_plan_path %>

app/views/user_product_plans/index.js.erb
$("#user_product_plans").html("<%= escape_javascript(render("user_product_plans")) %>");

app/views/user_product_plans/new.html.erb
<%= render 'form' %>

<% if params[:product_id]%>
 <%= button_to 'More Info', plan_value_product_info_path(:product_plan_id => ProductPlan.find_all_by_product_id(params[:product_id]).first.id.to_i), :method => :get %>
<%end%>
 <br><%= link_to 'Back', user_product_plans_path %><br><br>

app/views/user_product_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @user_product_plan.user_id %>
</p>

<p>
  <b>Product :</b>
  <%= @user_product_plan.product_id %>
</p>

<p>
  <b>Product Plan:</b>
  <%= @user_product_plan.product_plan_id %>
</p>


<%= link_to 'Edit', edit_user_product_plan_path(@user_product_plan) %> |
<%= link_to 'Back', user_product_plan_path %>