config/routes.rb
Trackkr002::Application.routes.draw do
  
  
  default_url_options :host => "localhost:3000" 

  resources :share_dashboards

  get "share/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :user_product_plan_graphs
  
  #get "password_resets/new"
  resources :password_resets

  resources :user_product_plan_datas do
   post 'edit_individual', :on => :collection
   put 'update_individual', :on => :collection
  end

  resources :product_plans

  resources :plan_values

  resources :friendships

  root :to => "trackkr_modules#index"
 
  resources :graphs

  resources :user_product_plans
  get 'user_product_plan_graphs/new/:user_product_plan_id' => 'user_product_plan_graphs#new', :as => :new_graph_plan
  get 'user_product_plans/product/:product_id' => 'user_product_plans#new', :as => "add_new_user_product_plan"
  get 'plan_values/product/:product_plan_id' => 'plan_values#index', :as => "plan_value_product_info"
# the above are named routes - so we can call them using :as and the url that will be matched

  resources :dashboards 
  
  
  match  "/sample_dashboard" => "info#sample_dashboard", :as => :sample_dashboard
  match  "/about" => "info#About", :as => :About
  match  "/partners" => "info#Partners", :as => :Partners
  match  "/contact" => "info#Contact", :as => :Contact
  match  "/carriers" => "info#Carriers", :as => :Carriers
  match  "/help" => "info#Help", :as => :Help
  
resources :t_categories do
  resources :products do
    put 'select', :on => :collection
  end
end

  resources :trackkr_modules do
    resources :t_categories
  end
 
  resources :user_sessions
  
  get "login" => "user_sessions#new", :as => "login"
  get "logout" => "user_sessions#destroy", :as => "logout"
  
  get "add_to_cart/:product_id" => "user_products#add_to_cart",:as=>"add_to_cart"
  get "add_to_cart/:product_id/friend/:friend_id" => "user_products#add_to_cart",:as=>"add_to_cart_with_frd"  
  
  get "user_search" => "friendships#search", :as => "user_search"
  get "send_invite" => "friendships#send_invite",:as =>"send_invite"
  resources :users

end

app/models/t_category.rb
  class TCategory < ActiveRecord::Base
  validates :name, :image_location, :trackkr_module_id, :presence => true
  belongs_to :trackkr_module
  has_many :graphs
  has_many :products, :dependent => :destroy
  scope :sports, where(:trackkr_module_id => '1')
  
  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/t_categories_controller.rb
class TCategoriesController < ApplicationController
  before_filter :authorize, :except => :index
  
  respond_to :html  
  
  def index
    @t_categories = trackkr_module.t_categories.search(params[:search])
    
    respond_with [@t_categories, @trackkr_module]
  end
  
  def new
    @t_category = trackkr_module.t_categories.new
    
    respond_with [trackkr_module, @t_category]
    
  end
   
  def create
    @t_category = trackkr_module.t_categories.new(params[:t_category])
    
    respond_with [trackkr_module, @t_category] do |format|
      format.html {
      if @t_category.save
        flash[:notice] = 'The category was saved'
        redirect_to(trackkr_module_t_categories_path())
      else
        render 'new'
      end
      }
    end
  end
  
  def edit
    @t_category = trackkr_module.t_categories.find(params[:id])
    
    respond_with [trackkr_module, @t_category]
    
  end
   
  def update
    @t_category = trackkr_module.t_categories.find(params[:id])
    
    update_was_successful = @t_category.update_attributes(params[:t_category])
    
    respond_with [trackkr_module, @t_category] do |format|
      format.html {
      if update_was_successful
        flash[:notice] = 'The category was updated'
        redirect_to(trackkr_module_t_categories_path())
      else
        render 'edit'
      end
      }
    end
  end
  
  def destroy
    t_category = trackkr_module.t_categories.find(params[:id])
    if t_category.destroy
      flash[:notice] = 'The role was destroyed'
    else
      flash[:alert] = 'The role could not be destroyed'
    end
    
    respond_with [trackkr_module, t_category] do |format|
      format.html {redirect_to(trackkr_module_t_categories_path())}
    end
  end
  
  private
  def trackkr_module
    @trackkr_module ||= TrackkrModule.find(params[:trackkr_module_id])    
  end
end

app/views/t_categories/_form.html.erb
<%= semantic_form_for [@t_category.trackkr_module, @t_category] do |form| %>
	<%= form.inputs %>
	<%= form.buttons %>
<% end %>

app/views/t_categories/edit.html.erb
<%= render :partial => 'form' %>

app/views/t_categories/index.html.erb
<br>
<b>CATEGORIES in <%= @trackkr_module.name %> </b><br>
<%= form_tag  trackkr_module_t_categories_path, :method => "get" do %>
		<%= render 'shared/search_box' %>
<% end %>


<% @t_categories.each do |category| %>
<div class="<%= cycle('marketingPanelPosition1', 'marketingPanelPosition2') %>">
	<%= category.name %>
	<%= link_to(image_tag(category.image_location), t_category_products_path(category.id)) %><br>
	<% if current_user %>
		<% if current_user.username == 'admin' %>
			<%= link_to 'Edit', edit_trackkr_module_t_category_path(category.trackkr_module_id, category.id) %>
			<%= link_to 'Delete', trackkr_module_t_category_path(category.trackkr_module_id, category.id),
		:confirm => 'Are you sure', :method => :delete %>
		<% end %>
	<% end %>
	<%= link_to 'View Products', t_category_products_path(category.id) %><br>
</div>
<% end %>
<% if current_user %>
	<% if current_user.username == 'admin' %>
		<td><%= link_to 'Add Categories', new_trackkr_module_t_category_path(@trackkr_module) %></td><br><br>
	<% end %>
<% end %>
<%= link_to 'Back to Modules', trackkr_modules_path %>

app/views/t_categories/new.html.erb
<%= render :partial => 'form' %>