config/routes.rb
Trackkr002::Application.routes.draw do
  
  
  default_url_options :host => "localhost:3000" 

  resources :share_dashboards

  get "share/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :user_product_plan_graphs
  
  #get "password_resets/new"
  resources :password_resets

  resources :user_product_plan_datas do
   post 'edit_individual', :on => :collection
   put 'update_individual', :on => :collection
  end

  resources :product_plans

  resources :plan_values

  resources :friendships

  root :to => "trackkr_modules#index"
 
  resources :graphs

  resources :user_product_plans
  get 'user_product_plan_graphs/new/:user_product_plan_id' => 'user_product_plan_graphs#new', :as => :new_graph_plan
  get 'user_product_plans/product/:product_id' => 'user_product_plans#new', :as => "add_new_user_product_plan"
  get 'plan_values/product/:product_plan_id' => 'plan_values#index', :as => "plan_value_product_info"
# the above are named routes - so we can call them using :as and the url that will be matched

  resources :dashboards 
  
  
  match  "/sample_dashboard" => "info#sample_dashboard", :as => :sample_dashboard
  match  "/about" => "info#About", :as => :About
  match  "/partners" => "info#Partners", :as => :Partners
  match  "/contact" => "info#Contact", :as => :Contact
  match  "/carriers" => "info#Carriers", :as => :Carriers
  match  "/help" => "info#Help", :as => :Help
  
resources :t_categories do
  resources :products do
    put 'select', :on => :collection
  end
end

  resources :trackkr_modules do
    resources :t_categories
  end
 
  resources :user_sessions
  
  get "login" => "user_sessions#new", :as => "login"
  get "logout" => "user_sessions#destroy", :as => "logout"
  
  get "add_to_cart/:product_id" => "user_products#add_to_cart",:as=>"add_to_cart"
  get "add_to_cart/:product_id/friend/:friend_id" => "user_products#add_to_cart",:as=>"add_to_cart_with_frd"  
  
  get "user_search" => "friendships#search", :as => "user_search"
  get "send_invite" => "friendships#send_invite",:as =>"send_invite"
  resources :users

end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
 helper_method :check_if_record_exists
  before_filter :require_user
  # GET /dashboards
  # GET /dashboards.xml
  def index
    current_user
    @date = params[:month] ? Date.parse(params[:month].gsub('-', '/')) : Date.today
    @user_product_plans = current_user.user_product_plans.all
    #session[:product_plan_id] = params[:product_plan_id] || current_user.user_product_plans.first.product_plan_id
    session[:user_product_plan_id] = params[:user_product_plan_id] || current_user.user_product_plans.first.id
    #session[:friend_product_plan_id] = UserProductPlanGraph.find(session[:user_product_plan_id]).friend_product_plan_id
    session[:product_id] = UserProductPlan.find(session[:user_product_plan_id]).product_plan.product.id
    @user_product_plan_graphs = UserProductPlanGraph.find_all_by_user_product_plan_id(session[:user_product_plan_id])
    #session[:friend_product_plan_id] = @user_product_plan_graphs.friend_product_plan_id
    @user_product_plan = UserProductPlan.find(session[:user_product_plan_id])
    @user_product_plan_datas = UserProductPlanData.by_days(14).unfilled_actual_data.find_all_by_user_product_plan_id(session[:user_product_plan_id])
    @user_product_plan_datas_actual_distance= @user_product_plan_datas.find(:actual_distance)
    @friendships = Friendship.find_all_by_user_id_and_product_id(current_user.id,session[:product_id])
    @inverse_friendships = current_user.inverse_friendships.find_all_by_product_id_and_friend_id(session[:product_id], current_user)
    @graphs = Graph.find_all_by_t_category_id(session[:t_category])
    respond_to do |format|
      #UserMailer.share(@user).deliver
      format.html # index.html.erb
      format.xml  { render :xml => @dashboards }
    end
  end

  # GET /dashboards/1
  # GET /dashboards/1.xml
  def show
    @dashboard = Dashboard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dashboard }
    end
  end

  # GET /dashboards/new
  # GET /dashboards/new.xml
  def new
    @dashboard = Dashboard.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dashboard }
    end
  end

  # GET /dashboards/1/edit
  def edit
    @dashboard = Dashboard.find(params[:id])
  end

  # POST /dashboards
  # POST /dashboards.xml
  def create
    @dashboard = Dashboard.new(params[:dashboard])

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to(@dashboard, :notice => 'Dashboard was successfully created.') }
        format.xml  { render :xml => @dashboard, :status => :created, :location => @dashboard }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dashboard.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dashboards/1
  # PUT /dashboards/1.xml
  def update
    @dashboard = Dashboard.find(params[:id])

    respond_to do |format|
      if @dashboard.update_attributes(params[:dashboard])
        format.html { redirect_to(@dashboard, :notice => 'Dashboard was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dashboard.errors, :status => :unprocessable_entity }
      end
    end
  end

  
  # DELETE /dashboards/1
  # DELETE /dashboards/1.xml
  def destroy
    @dashboard = Dashboard.find(params[:id])
    @dashboard.destroy

    respond_to do |format|
      format.html { redirect_to(dashboards_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_form.html.erb
<%= form_for(@dashboard) do |f| %>
  <% if @dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% @dashboard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboards/_highchart.html.erb
<script type="text/javascript" charset="utf-8">
  $(function() {
    new Highcharts.Chart({
      chart: {
        renderTo: "user_chart",
defaultSeriesType: 'line'
      },
      title: {
        text: "Distance by Day"
      },
	  
   
	  
	  credits: {
		text: "trackkr ",
		href: "www.trackkr.com"
	   },
      xAxis: {
        type: "datetime"
      },
      yAxis: {
        title: {
          text: "Distance"
        }
      },
      series: [{
	  	name: "Actual",
		pointInterval: <%= 1.day * 1000 %>,
		pointStart: <%= 5.weeks.ago.to_i * 1000 %>,  
	  	data: <%= (5.weeks.ago.to_date..Date.today).map {|date| UserProductPlanData.user_actual_distance(date, session[:user_product_plan_id])}.inspect%>
		}, {
	  	name: "Planned",
		pointInterval: <%= 1.day * 1000 %>,
		pointStart: <%= 5.weeks.ago.to_i * 1000 %>,  
		data: <%= (5.weeks.ago.to_date..Date.today).map {|date| UserProductPlanData.user_plan_distance(date, session[:user_product_plan_id])}.inspect%>

		}]
       });
	   

  });
  
</script> 

app/views/dashboards/_highchart1.html.erb
<script type="text/javascript" charset="utf-8">
	$(function(){
		new Highcharts.Chart({
			chart: {
				renderTo: 'graph_1_<%= user_product_plan_graph.friend_product_plan_id || session[:user_product_plan_id] %>',
				height: 250,
				width: 450,
				backgroundColor: '#FCFFC5',
				defaultSeriesType: '<%= @graph_select_type %>'
			},
			tooltip:{
				backgroundColor: '#008000'
			},
			legend: {
				
				backgroundColor: '#008000',
			},
			
			title: {
				text: "Graph - 1"
			},
			
			plotOptions: {
				series: {
            	allowPointSelect: true}
        	},
			credits: {
				text: "trackkr",
				href: "www.trackkr.com"
			},
      		xAxis: {
        		type: "datetime"
      		},
      		yAxis: {
        		title: {
          		text: "Distance"
        	}},
      		series: [{
	  			name: "Actual",
				pointInterval: <%= 1.day * 1000 %>,
				pointStart: <%= @graph_select_range.to_i * 1000 %>,  
	  			data: <%= (@graph_select_range.to_date..Date.today).map {|date| UserProductPlanData.user_actual_distance(date, user_product_plan_graph.friend_product_plan_id) || session[:user_product_plan_id]}.inspect%>
			},
			{
	  			name: "Planned",
				pointInterval: <%= 1.day * 1000 %>,
				pointStart: <%= @graph_select_range.to_i * 1000 %>,  
				data: <%= (@graph_select_range.to_date..Date.today).map {|date| UserProductPlanData.user_plan_distance(date, user_product_plan_graph.friend_product_plan_id) || session[:user_product_plan_id]}.inspect%>
		}]
      });
    });
  </script> 
 
 
 
  <div id="graph_1_<%=user_product_plan_graph.friend_product_plan_id || session[:user_product_plan_id]%>" style="width:560px; height:300px;"> </div>

	
	

app/views/dashboards/_highchart2.html.erb
<script type="text/javascript" charset="utf-8">
	$(function(){
		new Highcharts.Chart({
			chart: {
				renderTo: 'graph_2_<%= user_product_plan_graph.friend_product_plan_id || session[:user_product_plan_id] %>',
				height: 250,
				width: 450,
				backgroundColor: '#8A949E',
				defaultSeriesType: '<%= @graph_select_type %>'
			},
			
			title: {
				text: "Graph - 2"
			},
			
			plotOptions: {
				series: {
            	allowPointSelect: true}
        	},
			credits: {
				text: "trackkr",
				href: "www.trackkr.com"
			},
      		xAxis: {
        	type: "datetime"
      		},
      		yAxis: {
        	title: {
          	text: "Distance"
        	}},
      	series: [{
	  		name: "Actual",
			pointInterval: <%= 1.day * 1000 %>,
			pointStart: <%= @graph_select_range.to_i * 1000 %>,  
	  		data: <%= (@graph_select_range.to_date..Date.today).map {|date| UserProductPlanData.user_actual_speed(date,user_product_plan_graph.friend_product_plan_id || session[:user_product_plan_id])}.inspect%>
			},
			{
	  		name: "Planned",
			pointInterval: <%= 1.day * 1000 %>,
			pointStart: <%= @graph_select_range.to_i * 1000 %>,  
			data: <%= (@graph_select_range.to_date..Date.today).map {|date| UserProductPlanData.user_plan_speed(date,user_product_plan_graph.friend_product_plan_id || session[:user_product_plan_id])}.inspect%>
		}]
      });
    });
  </script> 

<div id="graph_2_<%= user_product_plan_graph.friend_product_plan_id || session[:user_product_plan_id] %>" style="width:560px; height:300px;"> </div>	
	

app/views/dashboards/_highchart3.html.erb
<script type="text/javascript" charset="utf-8">
		$(function() {
    	new Highcharts.Chart({
      	chart: {
		        renderTo: 'graph_3_<%= user_product_plan_graph.friend_product_plan_id || session[:user_product_plan_id] %>',
		        height: 250,
				width: 450,
				backgroundColor: '#AAB2BA',
				defaultSeriesType: '<%= @graph_select_type %>'
    	 },
      		title: {
        	text: "Graph - 3"
      		},
			credits: {
			text: "trackkr ",
			href: "www.trackkr.com"
	   		},
      		xAxis: {
        	type: "datetime"
      		},
      		yAxis: {
        	title: {
          	text: "Distance"
        	}},
      	series: [{
	  		name: "Actual",
			pointInterval: <%= 1.day * 1000 %>,
			pointStart: <%= @graph_select_range.to_i * 1000 %>,  
	  		data: <%= (@graph_select_range.to_date..Date.today).map {|date| UserProductPlanData.user_actual_time(date,user_product_plan_graph.friend_product_plan_id || session[:user_product_plan_id])}.inspect%>
			},
			{
	  		name: "Planned",
			pointInterval: <%= 1.day * 1000 %>,
			pointStart: <%= @graph_select_range.to_i * 1000 %>,  
			data: <%= (@graph_select_range.to_date..Date.today).map {|date| UserProductPlanData.user_plan_time(date,user_product_plan_graph.friend_product_plan_id || session[:user_product_plan_id])}.inspect%>
		}]
      });
    });
  </script> 
 
	
<div id="graph_3_<%= user_product_plan_graph.friend_product_plan_id || session[:user_product_plan_id] %>" style="width:560px; height:300px;"> </div>	

app/views/dashboards/_highchart4.html.erb
<script type="text/javascript" charset="utf-8">
		$(function() {
    	new Highcharts.Chart({
      	chart: {
		        renderTo: 'graph_4_<%= user_product_plan_graph.friend_product_plan_id || session[:user_product_plan_id] %>',
		        height: 250,
				width: 450,
				backgroundColor: '#F4F4F4',
				defaultSeriesType: '<%= @graph_select_type %>'
    	 },
      		title: {
        	text: "Graph - 4"
      		},
			credits: {
			text: "trackkr ",
			href: "www.trackkr.com"
	   		},
      		xAxis: {
        	type: "datetime"
      		},
      		yAxis: {
        	title: {
          	text: "Distance"
        	}},
      	series: [{
	  		name: "Actual",
			pointInterval: <%= 1.day * 1000 %>,
			pointStart: <%= @graph_select_range.to_i * 1000 %>,  
	  		data: <%= (@graph_select_range.to_date..Date.today).map {|date| UserProductPlanData.user_actual_distance(date, user_product_plan_graph.friend_product_plan_id || session[:user_product_plan_id])}.inspect%>
			},
			{
	  		name: "Planned",
			pointInterval: <%= 1.day * 1000 %>,
			pointStart: <%= @graph_select_range.to_i * 1000 %>,  
			data: <%= (@graph_select_range.to_date..Date.today).map {|date| UserProductPlanData.user_plan_distance(date, user_product_plan_graph.friend_product_plan_id || session[:user_product_plan_id])}.inspect%>
		}]
      });
    });
  </script> 
 
	
	<div id="graph_4_<%= user_product_plan_graph.friend_product_plan_id || session[:user_product_plan_id] %>" style="width:560px; height:300px;"> </div>

app/views/dashboards/edit.html.erb
<h1>Editing dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @dashboard %> |
<%= link_to 'Back', dashboards_path %>

app/views/dashboards/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>trackkr-track your key results</title>
<style type="text/css">
<!--
body {
	margin-left: 0px;
	margin-top: 0px;
	margin-right: 0px;
	margin-bottom: 0px;
}
.white{
	background-color:#fff;
}
.red{
	background-color:red
}
.green{
	background-color:008000;
}
-->
</style>



<% @user_product_plan_graphs.each do |user_product_plan_graph| %>
  
  <div class="<%= cycle('user_graph1', 'user_graph2') %>">
  	
		<%if user_product_plan_graph.friend_product_plan_id == nil%>
			<p><%=User.find(UserProductPlan.find(user_product_plan_graph.user_product_plan_id).user_id).username%>
				<%= user_product_plan_graph.graph.name%></p>
		<%else%>
			<p> Friend's Name: <%=User.find(UserProductPlan.find(user_product_plan_graph.friend_product_plan_id).user_id).username%></p>
			<p>Friend's graphs name:<%= user_product_plan_graph.graph.name%></p>	
		<%end%>
		
		<%= @graph_select_type = user_product_plan_graph.graph_select_type.downcase%>
		<%= @graph_select_range = user_product_plan_graph.graph_select_range%>
		
		<% if @graph_select_range == "1 week" %>
			<% @graph_select_range = 1.week.ago %>
		<% elsif @graph_select_range == "1 month" %>
			<% @graph_select_range = 1.month.ago %>
		<% elsif @graph_select_range == "3 month" %>
			<% @graph_select_range = 3.month.ago %>
		 <%end%>
		 
	
	      
		<% if user_product_plan_graph.graph_id == @graphs.first.id %>
			<%= render 'dashboards/highchart1',:user_product_plan_graph => user_product_plan_graph %>
			  
		<% elsif user_product_plan_graph.graph_id == @graphs.second.id  %>
			<%= render 'dashboards/highchart2',:user_product_plan_graph => user_product_plan_graph  %>
			  
		<% elsif user_product_plan_graph.graph_id ==@graphs.third.id  %>
			<%= render 'dashboards/highchart3',:user_product_plan_graph => user_product_plan_graph %>
			 
		<% elsif user_product_plan_graph.graph_id ==@graphs.fourth.id  %>
			<%= render 'dashboards/highchart3',:user_product_plan_graph => user_product_plan_graph %>
			 	 
		<%end%>
	
    
</div>	
	
<% end %>


</head>
</br>
<body>
	
</div>	
 <div style="width:600px; height:350px"> </div>
<div id ="frd_network"> <%=link_to "Add Friend to Network",new_friendship_path(:product_id=>Product.first.id),{:rel=>"facebox[.bolder]"}%></div>
<div id="left"> My Friends:
<ul>	
	<% for friendship in @friendships%>
	<li>
	<%if friendship.status =="Accepted"%>
		<%= link_to User.find(friendship.friend_id).username, users_path%>
	<%elsif friendship.status =="Pending"%>
		<%= friendship.friend.username%>
	<%elsif friendship.status =="Rejected"%>
		<%= friendship.friend.id%>
	<%end%>
		<%= link_to "Remove", friendship, :method => :delete, :confirm => 'Are you sure'%>
		</li>
	<%end%>
</ul>


<div> Added Me as friend:</div>
  	<% if @inverse_friendships %>
  	<%for inverse_friendship in @inverse_friendships%> 
 	<li>
	<%= inverse_friendship.user.username %>
	</li>
	<%end%>
<% end %>
</div>

 

<div id="centre">  <strong>List of Plans I have registered to:</strong>
<ul>
	<% @user_product_plans.each do |user_product_plan|%>
	<% if user_product_plan.id == session[:user_product_plan_id].to_i%>
		<li>
			<p><strong><SPAN style="BACKGROUND-COLOR: #ffff00"><font size ="3"><%= user_product_plan.product_plan.product_plan_name%></font></strong></p>
		<%else %>
			<%= link_to user_product_plan.product_plan.product_plan_name, dashboards_path(:user_product_plan_id => user_product_plan.id) %>
		</li>
	
	<%end%>
<% end %>
	<%= button_to "Add new Plan", trackkr_modules_path, :method => :get%>
	
</ul>
</div>

<div style="height:100px;width:250px; overflow:auto;" id="right">	
  <p><strong>GOAL:</strong></p>
	<ul>
		 <p> Product Plan ID: <%= @user_product_plan.product_plan.product_plan_name %></p> 
		 <p> Start Date: 	  <%= @user_product_plan.start_date%></p>	
		 <p> End Date: 	  	  <%= @user_product_plan.end_date%></p>	
	</ul> 			
	
<%= button_to 'Destroy', @user_product_plan, :confirm => 'Are you sure? If you delete the product plan all your data will be lost', :method => :delete %>	
</div> 
</br>
</br>
</br>

<%= render 'user_product_plan_datas/edit_individual'%>	
<%= button_to "Home", trackkr_modules_path, :method => :get %>	
<%= button_to "Edit Chart Setting", new_user_product_plan_graph_path, :method => :get%>
 <!--<div id="user_chart"></div>-->

	
<div id="common">

<div class="regionhdr"> Calendar
<div id="calendar">
	<h2 id="month">
		<%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m"), :user_product_plan_id => session[:user_product_plan_id]%>
		<%= h @date.strftime("%B %Y")%>
		<%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m"), :user_product_plan_id => session[:user_product_plan_id]%>
	</h2> 
<%= calendar_for @user_product_plan_datas, :year => @date.year, :month => @date.month do |calendar| %>
	<%= calendar.head('Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat') %>
	<%= calendar.day(:day_method => :training_date) do |date, user_product_plan_datas|%>
	<%data = user_product_plan_datas_row(session[:user_product_plan_id] , date)%>
    <div class="<%=get_color(data)%>">
    	<%= link_to (date.day), "#{new_user_product_plan_data_path}?date=#{date}",:rel => "facebox[.bolder]" %>
	</div>

<% end %>
</div>
 <%= link_to "Big Calendar", user_product_plan_datas_path, :method => :get  %>
	<%end%>
</div>
<div>
	<%= link_to 'Share your trackkr', new_share_dashboard_path,:method => :get %>
</div>
</body>
</html>

app/views/dashboards/new.html.erb
<h1>New dashboard</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboards_path %>

app/views/dashboards/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_dashboard_path(@dashboard) %> |
<%= link_to 'Back', dashboards_path %>