config/routes.rb
Trackkr002::Application.routes.draw do
  
  
  default_url_options :host => "localhost:3000" 

  resources :share_dashboards

  get "share/index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :user_product_plan_graphs
  
  #get "password_resets/new"
  resources :password_resets

  resources :user_product_plan_datas do
   post 'edit_individual', :on => :collection
   put 'update_individual', :on => :collection
  end

  resources :product_plans

  resources :plan_values

  resources :friendships

  root :to => "trackkr_modules#index"
 
  resources :graphs

  resources :user_product_plans
  get 'user_product_plan_graphs/new/:user_product_plan_id' => 'user_product_plan_graphs#new', :as => :new_graph_plan
  get 'user_product_plans/product/:product_id' => 'user_product_plans#new', :as => "add_new_user_product_plan"
  get 'plan_values/product/:product_plan_id' => 'plan_values#index', :as => "plan_value_product_info"
# the above are named routes - so we can call them using :as and the url that will be matched

  resources :dashboards 
  
  
  match  "/sample_dashboard" => "info#sample_dashboard", :as => :sample_dashboard
  match  "/about" => "info#About", :as => :About
  match  "/partners" => "info#Partners", :as => :Partners
  match  "/contact" => "info#Contact", :as => :Contact
  match  "/carriers" => "info#Carriers", :as => :Carriers
  match  "/help" => "info#Help", :as => :Help
  
resources :t_categories do
  resources :products do
    put 'select', :on => :collection
  end
end

  resources :trackkr_modules do
    resources :t_categories
  end
 
  resources :user_sessions
  
  get "login" => "user_sessions#new", :as => "login"
  get "logout" => "user_sessions#destroy", :as => "logout"
  
  get "add_to_cart/:product_id" => "user_products#add_to_cart",:as=>"add_to_cart"
  get "add_to_cart/:product_id/friend/:friend_id" => "user_products#add_to_cart",:as=>"add_to_cart_with_frd"  
  
  get "user_search" => "friendships#search", :as => "user_search"
  get "send_invite" => "friendships#send_invite",:as =>"send_invite"
  resources :users

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :image_location, :presence => true
  belongs_to :t_category
  has_many :product_plans
  
  def self.search(search)
   if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
        find(:all)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authorize, :except => :index
  
  respond_to :html
  
  def index
    @products = t_category.products.search(params[:search])
  end
  
  def new
    @product = t_category.products.new
    
    respond_with [@product, t_category]
  end
  
  def create
    @product = t_category.products.new(params[:product])
    
    respond_with [@product, t_category] do |format|
      format.html {
      if @product.save
        flash[:notice] = 'The Product was successfully created'
        redirect_to(t_category_products_path())
      else
        render 'new'
      end
      }
    end
    
  end
  
  
    def edit
    @product = t_category.products.find(params[:id])
    
    respond_with [@product, t_category]
  end
  
  def update
    @product = t_category.products.find(params[:id])
    
    update_was_successful = @product.update_attributes(params[:product])
    
    respond_with [@product, t_category] do |format|
      format.html {
      if update_was_successful
        flash[:notice] = 'The Product was successfully updated'
        redirect_to(t_category_products_path())
      else
        render 'edit'
      end
      }
    end
    
  end
  
   def destroy
    product = t_category.products.find(params[:id])
    
    if product.destroy
      flash[:notice] = 'The role was destroyed'
    else
      flash[:alert] = 'The role could not be destroyed'
    end
    
    respond_with [product, t_category] do |format|
      format.html {redirect_to(t_category_products_path())}
    end
  end
  
  
  private
  def t_category
    @t_category ||= TCategory.find(params[:t_category_id])
  end
  
end

app/views/products/_form.html.erb
<%= semantic_form_for [@product.t_category, @product] do |form| %>
	<%= form.inputs %>
	<%= form.buttons %>
<% end %>

app/views/products/edit.html.erb
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<br>
<b> PRODUCTS IN <%= @t_category.name %></b>
<br>
<%= form_tag  t_category_products_path, :method => "get" do %>
		<%= render 'shared/search_box' %>
<% end %>
<% @products.each do |product| %>
<div class="<%= cycle('marketingPanelPosition1', 'marketingPanelPosition2') %>">
	<p><%= product.name %>
	<%= image_tag(product.image_location)  %>
	<% if current_user %>
		<% if current_user.username == 'admin' %>
			<%= link_to 'Edit', edit_t_category_product_path(product.t_category_id, product.id) %>
			<%= link_to 'Delete', t_category_product_path(product.t_category_id, product.id),
				:confirm => 'Are you sure', :method => :delete %>
		<% end %>
	<% end %>
	</p>
	<div style="float: left; width: auto;">

    	<%= button_to 'Get started', add_new_user_product_plan_path(:product_id => product.id), :method => :get %> 
	</div>
	<% if ProductPlan.find_all_by_product_id(product.id).first %>
    <div style="float: left; width: auto;">
	  <%= button_to 'More Info', plan_value_product_info_path(:product_plan_id => ProductPlan.find_all_by_product_id(product.id).first), :method => :get %>
	</div>
	<% end %>

	<br>
</div>
<% end %>
<% if current_user %>
	<% if current_user.username == 'admin' %>
		<td><%= link_to 'Add Products', new_t_category_product_path(@t_category) %></td><br><br>
	<% end %>
<% end %>
<%= link_to 'Back to Modules', trackkr_modules_path %>

app/views/products/new.html.erb
<%= render :partial => 'form' %>